clear_all_shortcuts yes
map cmd+q quit
#bell_off
enable_audio_bell no
#include ~/.config/kitty/BirdsOfParadise.conf
font_family JetBrains Mono Nerd Font
font_size 15
enable_ligatures no
confirm_exit no
confirm_os_window_close 0

enabled_layouts vertical, grid, horizontal

#map opt+shift+j next_window
#map opt+shift+k previous_window

map opt+s new_window
map opt+t new_tab
map opt+j next_window
map opt+k previous_window
map opt+h previous_tab
map opt+l next_tab

map opt+shift+h previous_tab
map opt+shift+l next_tab
#map opt+shift+o next_layout
map opt+o next_layout

#map opt+h previous_window
#map opt+l next_window

map opt+c copy_to_clipboard
map opt+v paste_from_clipboard
map cmd+c copy_to_clipboard
map cmd+v paste_from_clipboard
active_border_color   #FABD2F
inactive_border_color #5c6370
window_border_width 2

paste_actions quote-urls-at-prompt

map opt+left send_text all \x01
map opt+right send_text all \x05
map cmd+left send_text all \x01
map cmd+right send_text all \x05

scrollback_lines 50000
scrollback_pager_history_size 10000

cursor_beam_thickness 1.5
# cursor #fffff0
# cursor_text_color #111111

#enable_mouse_reporting yes
#open_url_with open

map opt+w close_window

# BEGIN_KITTY_THEME
# Gruvbox Dark
include current-theme.conf
# END_KITTY_THEME
map ctrl+l clear_terminal scroll active

# Search / scrollback
map opt+f show_scrollback
map opt+shift+f launch --type=overlay --stdin-source=@screen_scrollback --stdin-add-formatting sh -c 'grep --color=always -i "$1" || true' _ {kitty_mod}
map opt+u scroll_page_up
map opt+d scroll_page_down
map opt+g scroll_home
map opt+shift+g scroll_end

map cmd+f show_scrollback
map cmd+shift+f launch --type=overlay --stdin-source=@screen_scrollback --stdin-add-formatting sh -c 'grep --color=always -i "$1" || true' _ {kitty_mod}
map cmd+u scroll_page_up
map cmd+d scroll_page_down
map cmd+g scroll_home
map cmd+shift+g scroll_end
